server :
  port : 8080


spring :
  datasource :
    url :               jdbc:mariadb://localhost:3308/board
    password :          root
    username :          root
    driver-class-name : org.mariadb.jdbc.Driver
  jpa :
    show-sql :     true
    hibernate :
      ddl-auto : update

  redis :
    lettuce :
      pool :
        max-active : 10
        max-idle :   8
        min-idle :   2

    port : 6379
    host : localhost
  devtools :
    restart :
      enabled : true
      poll-interval : 2s
      quiet-period : 800ms
